name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: 安装jdk8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: 构建apk文件
      run: ./gradlew assembleDebug
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: app/build/outputs/apk/debug/app-debug.apk
    - name: Checkout code
        uses: actions/checkout@master
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
         tag_name: ${{ github.ref }}
         release_name: Release ${{ github.ref }}
         body: |
            Changes in this Release
            - First Change
            - Second Change
         draft: false
         prerelease: false
